# k port-forward service/nginx 8081:80 -n app1 # Browse to http://localhost:8081
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: app1
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
