
# kubectl exec -it nginx -n app1 -- /bin/sh
# k port-forward pod/nginx 8081:80 -n app1 # Browse to http://localhost:8081
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: app1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP